version: "3"
services:
  combine:
    container_name: combine
    build: .
    environment:
      - MQTT_HOST=mqtt-broker
      - MQTT_PORT=1883
    privileged: true

networks:
    default:
        external:
            name: ab2-network
